import math
import random
import os

def write_obj(filename, vertices, indices, normals=None, uvs=None):
    with open(filename, 'w') as f:
        f.write(f"# Generated by Starlight Asset Tool\n")
        f.write(f"o {os.path.basename(filename).split('.')[0]}\n")
        
        for v in vertices:
            f.write(f"v {v[0]:.4f} {v[1]:.4f} {v[2]:.4f}\n")
            
        if uvs:
            for vt in uvs:
                f.write(f"vt {vt[0]:.4f} {vt[1]:.4f}\n")
        
        if normals:
            for vn in normals:
                f.write(f"vn {vn[0]:.4f} {vn[1]:.4f} {vn[2]:.4f}\n")
                
        # Indices are 1-based in OBJ
        for i in range(0, len(indices), 3):
            # Check bounds to avoid index out of range if logic fails
            if i+2 >= len(indices): break
            
            i1, i2, i3 = indices[i]+1, indices[i+1]+1, indices[i+2]+1
            
            if normals and uvs:
                f.write(f"f {i1}/{i1}/{i1} {i2}/{i2}/{i2} {i3}/{i3}/{i3}\n")
            elif normals:
                f.write(f"f {i1}//{i1} {i2}//{i2} {i3}//{i3}\n")
            else:
                f.write(f"f {i1} {i2} {i3}\n")

def create_cylinder(radius_bottom, radius_top, height, segments):
    vertices = []
    indices = []
    normals = []
    uvs = []
    
    # Side vertices
    for i in range(segments + 1):
        angle = 2 * math.pi * i / segments
        x = math.cos(angle)
        z = math.sin(angle)
        
        # Bottom ring
        vertices.append([x * radius_bottom, 0, z * radius_bottom])
        normals.append([x, 0, z]) # Approx normal
        uvs.append([i / segments, 0])
        
        # Top ring
        vertices.append([x * radius_top, height, z * radius_top])
        normals.append([x, 0, z])
        uvs.append([i / segments, 1])
        
    # Indices for sides
    for i in range(segments):
        bottom1 = i * 2
        top1 = i * 2 + 1
        bottom2 = (i * 2 + 2)
        top2 = (i * 2 + 3)
        
        # Triangle 1
        indices.extend([bottom1, top1, bottom2])
        # Triangle 2
        indices.extend([top1, top2, bottom2])
        
    return vertices, indices, normals, uvs

def create_pine_foliage():
    vertices = []
    indices = []
    normals = []
    uvs = []
    
    layers = 3
    base_height = 1.0
    layer_height = 1.2
    max_radius = 1.5
    segments = 7
    
    for l in range(layers):
        y_start = base_height + (l * layer_height * 0.8)
        h = layer_height
        r_bottom = max_radius * (1.0 - (l * 0.25))
        r_top = 0.0 # Cone
        
        base_v_idx = len(vertices)
        
        # Generator for this cone/frustum
        # Bottom ring
        for i in range(segments + 1):
            angle = 2 * math.pi * i / segments
            x = math.cos(angle)
            z = math.sin(angle)
            vertices.append([x * r_bottom, y_start, z * r_bottom])
            normals.append([x, 0.5, z])
            uvs.append([i/segments, 0])
            
        # Top tip
        vertices.append([0, y_start + h, 0])
        normals.append([0, 1, 0])
        uvs.append([0.5, 1])
        top_idx = base_v_idx + segments + 1
        
        # Faces
        for i in range(segments):
            # Triangle fan to top
            current = base_v_idx + i
            next_v = base_v_idx + i + 1
            indices.extend([current, top_idx, next_v])
            
            # Bottom cap (optional, skip for foliage optimization)

    return vertices, indices, normals, uvs

def create_rock():
    # Icosahedron-like Sphere based on random subdivision
    # Simple cube subdiv
    vertices = []
    indices = []
    normals = []
    uvs = []
    
    # 8 corners of a cube
    base_verts = [
        [-1,-1,-1], [1,-1,-1], [1,1,-1], [-1,1,-1],
        [-1,-1,1], [1,-1,1], [1,1,1], [-1,1,1]
    ]
    
    # Simple cube faces (quads -> tris)
    faces = [
        [0,1,2,3], [1,5,6,2], [5,4,7,6],
        [4,0,3,7], [3,2,6,7], [4,5,1,0]
    ]
    
    for v in base_verts:
        # Deform
        vx = v[0] + random.uniform(-0.3, 0.3)
        vy = v[1] + random.uniform(-0.3, 0.3)
        vz = v[2] + random.uniform(-0.3, 0.3)
        vertices.append([vx, vy, vz])
        # Normal approx normalized pos
        l = math.sqrt(vx*vx + vy*vy + vz*vz)
        normals.append([vx/l, vy/l, vz/l])
        uvs.append([0,0]) # Placeholder

    for f in faces:
        indices.extend([f[0], f[1], f[2]])
        indices.extend([f[0], f[2], f[3]])
        
    return vertices, indices, normals, uvs

if __name__ == "__main__":
    out_dir = "assets/models/generated"
    os.makedirs(out_dir, exist_ok=True)
    
    print("Generating Trunk...")
    v, i, n, u = create_cylinder(0.2, 0.1, 1.0, 6) # Base trunk
    write_obj(f"{out_dir}/trunk.obj", v, i, n, u)
    
    print("Generating Leaves...")
    v, i, n, u = create_pine_foliage()
    write_obj(f"{out_dir}/leaves.obj", v, i, n, u)
    
    print("Generating Rock...")
    v, i, n, u = create_rock()
    write_obj(f"{out_dir}/rock.obj", v, i, n, u)
    
    print("Done.")
